name: Release & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: divmora/.github/.github/workflows/node-release.yml@main
    with:
      package-manager: 'npm'
      node-version: '20'
      build-command: 'npm run build'
      publish-command: 'npm publish --workspaces --access public'
    secrets: inherit
