name: Release & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: divmora/.github/.github/workflows/node-release.yml@main
    with:
      package-manager: 'pnpm'
      node-version: '20'
      build-command: 'pnpm run build'
      publish-command: 'pnpm -r publish --access public'
    secrets: inherit
